# Generated by Django 3.0.3 on 2020-03-24 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_files_user'),
        ('posts', '0003_posts_user'),
        ('quiz_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(blank=True, to='files.Files')),
                ('post', models.ManyToManyField(blank=True, to='posts.Posts')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_types.QuizTypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quizzes',
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
