# Generated by Django 3.0.3 on 2020-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('used_in_tickets', models.BooleanField(blank=True, default=False, null=True)),
                ('used_in_comments', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Black List Words',
                'verbose_name_plural': 'Black List Words',
            },
        ),
    ]
