# Generated by Django 3.0.3 on 2020-04-08 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_config', '0002_blogconfig_about_author_post'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogconfig',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogconfig',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favicon', to='files.Files'),
        ),
        migrations.AddField(
            model_name='blogconfig',
            name='header_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_img', to='files.Files'),
        ),
    ]
