# Generated by Django 3.0.3 on 2020-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        ('quiz_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgroups',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='quizzes.Quizzes'),
        ),
    ]
