# Generated by Django 3.0.3 on 2020-03-26 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
        ('quiz_options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUserSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quizzes')),
                ('selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_options.QuizOptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz User Submissions',
                'verbose_name_plural': 'Quiz User Submissions',
            },
        ),
    ]
