# Generated by Django 3.0.3 on 2020-04-10 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_user_submissions', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('quiz_options', '0002_quizoptions_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizusersubmissions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quizzes'),
        ),
        migrations.AddField(
            model_name='quizusersubmissions',
            name='selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_options.QuizOptions'),
        ),
    ]
